services:
  - type: web
    name: accountauth-main
    env: python
    branch: main
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput
      gunicorn AccountAuth.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: accountauth-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: accountauth-redis
          type: redis
          property: connectionString
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false

  - type: redis
    name: accountauth-redis
    plan: free

databases:
  - name: accountauth-db
    plan: free
    postgresMajorVersion: 15
